dist: xenial
language: php
notifications: {email: false}
php: ['7.2', '7.3']

before_install:
  - curl --location --remote-name https://storage.googleapis.com/dart-archive/channels/dev/release/latest/sdk/dartsdk-linux-x64-release.zip
  - unzip dartsdk-linux-x64-release.zip -d ${TRAVIS_HOME}
  - export PATH="${TRAVIS_HOME}/dart-sdk/bin:${TRAVIS_HOME}/.pub-cache/bin:$PATH"
  - dart --version

install: pub get
script: pub run grinder test
after_success: pub run grinder coverage
