name: grinder_php_minify
version: 4.0.0

author: Cédric Belin <cedric@belin.io>
description: Grinder plug-in minifying PHP source code by removing comments and whitespace.
documentation: https://dev.belin.io/grinder-php-minify/api
homepage: https://dev.belin.io/grinder-php-minify

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  grinder: ^0.8.3
  http: ^0.12.0
  path: ^1.6.2
  where: ^5.1.0

dev_dependencies:
  build_runner: ^1.1.2
  build_test: ^0.10.3
  coverage: ^0.12.3
  coveralls: ^4.3.0
  test: ^1.5.1
