name: grinder_php_minify
version: 6.0.0

author: Cédric Belin <cedric@belin.io>
description: Grinder plug-in minifying PHP source code by removing comments and whitespace.
documentation: https://dev.belin.io/grinder-php-minify/api
homepage: https://dev.belin.io/grinder-php-minify
issue_tracker: https://github.com/cedx/grinder-php-minify/issues
repository: https://github.com/cedx/grinder-php-minify

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  glob: ^1.1.7
  grinder: ^0.8.3
  http: ^0.12.0
  path: ^1.6.4
  where: ^6.4.0

dev_dependencies:
  grinder_coveralls: ^2.0.0
  test: ^1.6.11
