name: grinder_php_minify
version: 6.2.0

description: Grinder plug-in minifying PHP source code by removing comments and whitespace.
homepage: https://docs.belin.io/grinder-php-minify
issue_tracker: https://git.belin.io/cedx/grinder-php-minify/issues
repository: https://git.belin.io/cedx/grinder-php-minify

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  glob: ^1.2.0
  grinder: ^0.8.5
  http: ^0.12.2
  path: ^1.7.0
  where: ^7.0.0

dev_dependencies:
  coverage: ^0.14.0
  coveralls: ^5.9.0
  test: ^1.15.3
