name: grinder_php_minify
version: 2.0.0

author: Cédric Belin <cedric@belin.io>
description: Grinder plug-in minifying PHP source code by removing comments and whitespace.
documentation: https://cedx.github.io/grinder-php-minify
homepage: https://github.com/cedx/grinder-php-minify

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  grinder: ^0.8.0
  http: ^0.11.3
  path: ^1.4.2
  where: ^2.1.1

dev_dependencies:
  coverage: ^0.9.2
  coveralls: ^2.0.1
  test: ^0.12.24
