name: grinder_php_minify
version: 4.3.0

author: Cédric Belin <cedric@belin.io>
description: Grinder plug-in minifying PHP source code by removing comments and whitespace.
documentation: https://dev.belin.io/grinder-php-minify/api
homepage: https://dev.belin.io/grinder-php-minify
issue_tracker: https://github.com/cedx/grinder-php-minify/issues
repository: https://github.com/cedx/grinder-php-minify

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  grinder: ^0.8.3
  http: ^0.12.0
  path: ^1.6.2
  where: ^6.1.0

dev_dependencies:
  build_runner: ^1.3.1
  build_test: ^0.10.7
  coverage: ^0.12.4
  coveralls: ^5.1.0
  test: ^1.6.2
