name: grinder_php_minify
version: 2.0.0

author: Cédric Belin <cedric@belin.io>
description: Grinder plug-in minifying PHP source code by removing comments and whitespace.
documentation: https://cedx.github.io/grinder-php-minify
homepage: https://github.com/cedx/grinder-php-minify

environment:
  sdk: '>=1.24.0 <2.0.0'

dependencies:
  grinder: ^0.8.1
  http: ^0.11.3
  path: ^1.5.1
  where: ^2.2.0

dev_dependencies:
  coverage: ^0.9.3
  coveralls: ^2.1.0
  test: ^0.12.29
