name: grinder_php_minify
version: 6.1.0

description: Grinder plug-in minifying PHP source code by removing comments and whitespace.
homepage: https://dev.belin.io/grinder-php-minify
issue_tracker: https://github.com/cedx/grinder-php-minify/issues
repository: https://github.com/cedx/grinder-php-minify

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  glob: ^1.1.7
  grinder: ^0.8.3
  http: ^0.12.0
  path: ^1.6.4
  where: ^6.6.0

dev_dependencies:
  coverage: ^0.13.6
  coveralls: ^5.7.0
  test: ^1.12.0
