name: grinder_php_minify
version: 0.1.0

author: Cédric Belin <cedric@belin.io>
description: Grinder plug-in minifying PHP source code by removing comments and whitespace.
documentation: https://cedx.github.io/grinder-php-minify
homepage: https://github.com/cedx/grinder-php-minify

environment:
  sdk: '>=1.23.0'

dependencies:
  coverage: ^0.9.2
  coveralls: ^1.0.0
  grinder: ^0.8.0
  http: ^0.11.3
  path: ^1.4.1
  which: ^0.1.3

dev_dependencies:
  test: ^0.12.20
