name: grinder_php_minify
version: 3.1.0

author: Cédric Belin <cedric@belin.io>
description: Grinder plug-in minifying PHP source code by removing comments and whitespace.
documentation: https://dev.belin.io/grinder-php-minify/api
homepage: https://dev.belin.io/grinder-php-minify

environment:
  sdk: '>=2.0.0-dev.69 <3.0.0'

dependencies:
  grinder: ^0.8.3
  http: ^0.11.3
  path: ^1.6.2
  where: ^4.1.0

dev_dependencies:
  analyzer: ^0.32.4
  coverage: ^0.12.1
  coveralls: ^3.0.0
  test: ^1.3.0
