name: grinder_php_minify
version: 2.0.0

author: Cédric Belin <cedric@belin.io>
description: Grinder plug-in minifying PHP source code by removing comments and whitespace.
documentation: https://dev.belin.io/grinder-php-minify
homepage: https://github.com/cedx/grinder-php-minify

environment:
  sdk: '>=2.0.0-dev.65 <2.0.0'

dependencies:
  grinder: ^0.8.2
  http: ^0.11.3
  path: ^1.6.1
  where: ^4.0.0

dev_dependencies:
  coverage: ^0.12.1
  coveralls: ^3.0.0
  test: ^1.2.0
