name: build
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Dart
        run: |
          wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip
          unzip dartsdk-linux-x64-release.zip -d ${HOME}
      - name: Set up PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: 7.4
          extensions: mbstring
      - name: Check environment
        run: |
          ${HOME}/dart-sdk/bin/dart --version
          ${HOME}/dart-sdk/bin/pub --version
          php --version
      - name: Fetch sources
        uses: actions/checkout@master
      - name: Install dependencies
        run: ${HOME}/dart-sdk/bin/pub get
      - name: Run tests
        run: ${HOME}/dart-sdk/bin/pub run grinder test
      - name: Collect code coverage
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: success()
        run: ${HOME}/dart-sdk/bin/pub run grinder coverage
