name: Continuous integration
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Dart
        run: |
          wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip
          unzip dartsdk-linux-x64-release.zip -d ${HOME}
          export PATH="${HOME}/dart-sdk/bin:${HOME}/.pub-cache/bin:$PATH"
      - name: Check environment
        run: |
          dart --version
          pub --version
          php --version
      - name: Fetch sources
        uses: actions/checkout@v1
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run grinder test
      - name: Collect code coverage
        env:
          CI: true
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: success()
        run: pub run grinder coverage
