name: Continuous integration
on:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Dart
        run: |
          wget https://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip
          unzip dartsdk-linux-x64-release.zip -d ${HOME}
      - name: Check environment
        run: |
          ${HOME}/dart-sdk/bin/dart --version
          ${HOME}/dart-sdk/bin/pub --version
          php --version
      - name: Fetch sources
        uses: actions/checkout@v1
      - name: Install dependencies
        run: ${HOME}/dart-sdk/bin/pub get
      - name: Run tests
        run: |
          pwd
          ${HOME}/dart-sdk/bin/pub run grinder test
      - name: Debug tests # TODO: remove the debug step!
        if: failure()
        run: |
          pwd
          cat .dart_tool/grinder_coveralls/test_*.dart
      - name: Collect code coverage
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: success()
        run: ${HOME}/dart-sdk/bin/pub run grinder coverage
